// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijvxcwjggrjoafwhbwxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqdnhjd2pnZ3Jqb2Fmd2hid3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjU2NTgsImV4cCI6MjA2MTU0MTY1OH0.5waD46z5MbpBESLDfBbajd1W4dKsVOgPiBTbtxC6hXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);